services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 5iw2-nest:/var/lib/postgresql/data
    ports:
      - 5432:5432

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  5iw2-nest: {}
